### ISSUE TITLE
Weighted Natural Mortality

### ISSUE THREAD

**Issue by Dave-Keith** [RaphMcDo/SEBDAM#15]
Develop a natural mortality index that is weighted by the biomass in each knot.

**Comment by RaphMcDo** [comment]
If you see this, could you clarify exactly what you mean by that? I'm sure we discussed it back then, but I can't figure out what exactly you mean

**Comment by Dave-Keith** [comment]
The overall natural mortality index, as I think I understand it, is just the average of the M in all the knots.  What we should do is have M from each knot be weighted by the biomass in that knot to get a biomass weighted M.

**Comment by RaphMcDo** [comment]
Added an option in data_setup for this, specify weighted_mean_m=T
